service: aws-lambda

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
functions:
  s3-lambda-api:
    handler: handler.main
    events:
      - httpApi:
          path: /
          method: get
